// Generated by `supabase gen types typescript --linked` (mirrored via MCP).
// Do not edit by hand. Re-run `pnpm supabase:gen-types` after any migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      child_immunizations: {
        Row: {
          child_id: string;
          created_at: string;
          given_at: string | null;
          id: string;
          immunization_code: string;
          note: string | null;
          status: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          child_id: string;
          created_at?: string;
          given_at?: string | null;
          id?: string;
          immunization_code: string;
          note?: string | null;
          status?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          child_id?: string;
          created_at?: string;
          given_at?: string | null;
          id?: string;
          immunization_code?: string;
          note?: string | null;
          status?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "child_immunizations_child_id_fkey";
            columns: ["child_id"];
            isOneToOne: false;
            referencedRelation: "children";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "child_immunizations_immunization_code_fkey";
            columns: ["immunization_code"];
            isOneToOne: false;
            referencedRelation: "immunization_schedule";
            referencedColumns: ["code"];
          },
        ];
      };
      child_milestones: {
        Row: {
          checked_at: string | null;
          child_id: string;
          created_at: string;
          id: string;
          milestone_id: string;
          note: string | null;
          status: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          checked_at?: string | null;
          child_id: string;
          created_at?: string;
          id?: string;
          milestone_id: string;
          note?: string | null;
          status?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          checked_at?: string | null;
          child_id?: string;
          created_at?: string;
          id?: string;
          milestone_id?: string;
          note?: string | null;
          status?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "child_milestones_child_id_fkey";
            columns: ["child_id"];
            isOneToOne: false;
            referencedRelation: "children";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "child_milestones_milestone_id_fkey";
            columns: ["milestone_id"];
            isOneToOne: false;
            referencedRelation: "milestones";
            referencedColumns: ["id"];
          },
        ];
      };
      children: {
        Row: {
          birth_date: string;
          birth_length_cm: number | null;
          birth_weight_kg: number | null;
          created_at: string;
          deleted_at: string | null;
          gestational_age_weeks: number | null;
          id: string;
          name: string;
          notes: string | null;
          sex: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          birth_date: string;
          birth_length_cm?: number | null;
          birth_weight_kg?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          gestational_age_weeks?: number | null;
          id?: string;
          name: string;
          notes?: string | null;
          sex: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          birth_date?: string;
          birth_length_cm?: number | null;
          birth_weight_kg?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          gestational_age_weeks?: number | null;
          id?: string;
          name?: string;
          notes?: string | null;
          sex?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      growth_measurements: {
        Row: {
          child_id: string;
          created_at: string;
          head_circumference_cm: number | null;
          height_cm: number | null;
          id: string;
          measured_at: string;
          measured_lying: boolean | null;
          muac_cm: number | null;
          note: string | null;
          sd_class: Json;
          updated_at: string;
          user_id: string;
          weight_kg: number | null;
          z_scores: Json;
        };
        Insert: {
          child_id: string;
          created_at?: string;
          head_circumference_cm?: number | null;
          height_cm?: number | null;
          id?: string;
          measured_at: string;
          measured_lying?: boolean | null;
          muac_cm?: number | null;
          note?: string | null;
          sd_class?: Json;
          updated_at?: string;
          user_id: string;
          weight_kg?: number | null;
          z_scores?: Json;
        };
        Update: {
          child_id?: string;
          created_at?: string;
          head_circumference_cm?: number | null;
          height_cm?: number | null;
          id?: string;
          measured_at?: string;
          measured_lying?: boolean | null;
          muac_cm?: number | null;
          note?: string | null;
          sd_class?: Json;
          updated_at?: string;
          user_id?: string;
          weight_kg?: number | null;
          z_scores?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "growth_measurements_child_id_fkey";
            columns: ["child_id"];
            isOneToOne: false;
            referencedRelation: "children";
            referencedColumns: ["id"];
          },
        ];
      };
      growth_standards: {
        Row: {
          age_months: number;
          created_at: string;
          indicator: string;
          l: number;
          m: number;
          s: number;
          sex: string;
          source: string | null;
          updated_at: string;
          x_value: number;
        };
        Insert: {
          age_months: number;
          created_at?: string;
          indicator: string;
          l: number;
          m: number;
          s: number;
          sex: string;
          source?: string | null;
          updated_at?: string;
          x_value?: number;
        };
        Update: {
          age_months?: number;
          created_at?: string;
          indicator?: string;
          l?: number;
          m?: number;
          s?: number;
          sex?: string;
          source?: string | null;
          updated_at?: string;
          x_value?: number;
        };
        Relationships: [];
      };
      immunization_schedule: {
        Row: {
          code: string;
          created_at: string;
          display_order: number;
          dose_number: number | null;
          name: string;
          notes: string | null;
          prevents: string | null;
          recommended_age_months: number | null;
          updated_at: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          display_order?: number;
          dose_number?: number | null;
          name: string;
          notes?: string | null;
          prevents?: string | null;
          recommended_age_months?: number | null;
          updated_at?: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          display_order?: number;
          dose_number?: number | null;
          name?: string;
          notes?: string | null;
          prevents?: string | null;
          recommended_age_months?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      indicator_dictionary: {
        Row: {
          code: string;
          created_at: string;
          description: string | null;
          dimension: string;
          effect_direction: string | null;
          name: string;
          source_label: string | null;
          source_url: string | null;
          unit: string | null;
          updated_at: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          description?: string | null;
          dimension: string;
          effect_direction?: string | null;
          name: string;
          source_label?: string | null;
          source_url?: string | null;
          unit?: string | null;
          updated_at?: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          description?: string | null;
          dimension?: string;
          effect_direction?: string | null;
          name?: string;
          source_label?: string | null;
          source_url?: string | null;
          unit?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      milestones: {
        Row: {
          code: string;
          created_at: string;
          description: string;
          display_order: number;
          domain: string;
          id: string;
          max_age_months: number;
          min_age_months: number;
          source_label: string | null;
          updated_at: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          description: string;
          display_order?: number;
          domain: string;
          id?: string;
          max_age_months: number;
          min_age_months: number;
          source_label?: string | null;
          updated_at?: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          description?: string;
          display_order?: number;
          domain?: string;
          id?: string;
          max_age_months?: number;
          min_age_months?: number;
          source_label?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      model_coefficients: {
        Row: {
          coefficient: number;
          created_at: string;
          id: string;
          is_inference: boolean;
          kode_bps: string;
          model_version: string;
          predictor_code: string;
          se: number | null;
          tahun: number;
          updated_at: string;
        };
        Insert: {
          coefficient: number;
          created_at?: string;
          id?: string;
          is_inference?: boolean;
          kode_bps: string;
          model_version: string;
          predictor_code: string;
          se?: number | null;
          tahun: number;
          updated_at?: string;
        };
        Update: {
          coefficient?: number;
          created_at?: string;
          id?: string;
          is_inference?: boolean;
          kode_bps?: string;
          model_version?: string;
          predictor_code?: string;
          se?: number | null;
          tahun?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "model_coefficients_kode_bps_fkey";
            columns: ["kode_bps"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["kode_bps"];
          },
          {
            foreignKeyName: "model_coefficients_model_version_fkey";
            columns: ["model_version"];
            isOneToOne: false;
            referencedRelation: "model_metadata";
            referencedColumns: ["version"];
          },
          {
            foreignKeyName: "model_coefficients_predictor_code_fkey";
            columns: ["predictor_code"];
            isOneToOne: false;
            referencedRelation: "indicator_dictionary";
            referencedColumns: ["code"];
          },
        ];
      };
      model_metadata: {
        Row: {
          created_at: string;
          hyperparameters: Json;
          is_default: boolean;
          metrics: Json;
          moran_per_year: Json;
          name: string;
          notes: string | null;
          updated_at: string;
          version: string;
        };
        Insert: {
          created_at?: string;
          hyperparameters?: Json;
          is_default?: boolean;
          metrics?: Json;
          moran_per_year?: Json;
          name: string;
          notes?: string | null;
          updated_at?: string;
          version: string;
        };
        Update: {
          created_at?: string;
          hyperparameters?: Json;
          is_default?: boolean;
          metrics?: Json;
          moran_per_year?: Json;
          name?: string;
          notes?: string | null;
          updated_at?: string;
          version?: string;
        };
        Relationships: [];
      };
      model_predictions: {
        Row: {
          created_at: string;
          id: string;
          kode_bps: string;
          model_version: string;
          predicted_category: string;
          prob_rendah: number | null;
          prob_sedang: number | null;
          prob_tinggi: number | null;
          tahun: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          kode_bps: string;
          model_version: string;
          predicted_category: string;
          prob_rendah?: number | null;
          prob_sedang?: number | null;
          prob_tinggi?: number | null;
          tahun: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          kode_bps?: string;
          model_version?: string;
          predicted_category?: string;
          prob_rendah?: number | null;
          prob_sedang?: number | null;
          prob_tinggi?: number | null;
          tahun?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "model_predictions_kode_bps_fkey";
            columns: ["kode_bps"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["kode_bps"];
          },
          {
            foreignKeyName: "model_predictions_model_version_fkey";
            columns: ["model_version"];
            isOneToOne: false;
            referencedRelation: "model_metadata";
            referencedColumns: ["version"];
          },
        ];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          display_name: string | null;
          locale: string;
          role: string;
          theme_preference: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string | null;
          locale?: string;
          role?: string;
          theme_preference?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          display_name?: string | null;
          locale?: string;
          role?: string;
          theme_preference?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      region_boundaries: {
        Row: {
          created_at: string;
          geometry: Json;
          kode_bps: string;
          simplification_tolerance: number | null;
          source: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          geometry: Json;
          kode_bps: string;
          simplification_tolerance?: number | null;
          source?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          geometry?: Json;
          kode_bps?: string;
          simplification_tolerance?: number | null;
          source?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "region_boundaries_kode_bps_fkey";
            columns: ["kode_bps"];
            isOneToOne: true;
            referencedRelation: "regions";
            referencedColumns: ["kode_bps"];
          },
        ];
      };
      region_indicators: {
        Row: {
          created_at: string;
          id: string;
          kode_bps: string;
          tahun: number;
          updated_at: string;
          x1: number | null;
          x10: number | null;
          x11: number | null;
          x12: number | null;
          x13: number | null;
          x14: number | null;
          x15: number | null;
          x16: number | null;
          x17: number | null;
          x18: number | null;
          x19: number | null;
          x2: number | null;
          x20: number | null;
          x3: number | null;
          x4: number | null;
          x5: number | null;
          x6: number | null;
          x7: number | null;
          x8: number | null;
          x9: number | null;
          y_category: string;
          y1_prevalence: number | null;
        };
        Insert: {
          created_at?: string;
          id?: string;
          kode_bps: string;
          tahun: number;
          updated_at?: string;
          x1?: number | null;
          x10?: number | null;
          x11?: number | null;
          x12?: number | null;
          x13?: number | null;
          x14?: number | null;
          x15?: number | null;
          x16?: number | null;
          x17?: number | null;
          x18?: number | null;
          x19?: number | null;
          x2?: number | null;
          x20?: number | null;
          x3?: number | null;
          x4?: number | null;
          x5?: number | null;
          x6?: number | null;
          x7?: number | null;
          x8?: number | null;
          x9?: number | null;
          y_category: string;
          y1_prevalence?: number | null;
        };
        Update: {
          created_at?: string;
          id?: string;
          kode_bps?: string;
          tahun?: number;
          updated_at?: string;
          x1?: number | null;
          x10?: number | null;
          x11?: number | null;
          x12?: number | null;
          x13?: number | null;
          x14?: number | null;
          x15?: number | null;
          x16?: number | null;
          x17?: number | null;
          x18?: number | null;
          x19?: number | null;
          x2?: number | null;
          x20?: number | null;
          x3?: number | null;
          x4?: number | null;
          x5?: number | null;
          x6?: number | null;
          x7?: number | null;
          x8?: number | null;
          x9?: number | null;
          y_category?: string;
          y1_prevalence?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "region_indicators_kode_bps_fkey";
            columns: ["kode_bps"];
            isOneToOne: false;
            referencedRelation: "regions";
            referencedColumns: ["kode_bps"];
          },
        ];
      };
      regions: {
        Row: {
          created_at: string;
          kabupaten_kota: string;
          kode_bps: string;
          latitude: number | null;
          longitude: number | null;
          provinsi: string;
          tipe: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          kabupaten_kota: string;
          kode_bps: string;
          latitude?: number | null;
          longitude?: number | null;
          provinsi: string;
          tipe: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          kabupaten_kota?: string;
          kode_bps?: string;
          latitude?: number | null;
          longitude?: number | null;
          provinsi?: string;
          tipe?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      is_admin: { Args: never; Returns: boolean };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
