/**
 * Content-Security-Policy configuration (project guidelines Section 6).
 *
 * The policy is nonce-based: `src/proxy.ts` generates a fresh nonce per
 * request, forwards it to the RSC render via the {@link CSP_NONCE_HEADER}
 * request header (Next.js also reads the `content-security-policy` request
 * header and stamps the nonce onto its own inline bootstrap scripts), and
 * sets the enforcing or report-only header on the response.
 *
 * Allowlist rationale:
 * - `script-src 'strict-dynamic'`: scripts loaded by nonce-approved scripts
 *   (Next's chunk loader) are trusted transitively; host allowlists are
 *   ignored by modern browsers when present, so the policy stays short.
 * - `style-src 'unsafe-inline'`: React/motion/Recharts write `style`
 *   attributes; hashing every inline style is not practical today.
 * - Supabase (REST + Realtime websocket + Storage avatars), Google OAuth
 *   avatars, OpenFreeMap tiles/styles/glyphs, and Sentry ingest are the only
 *   external origins the browser talks to.
 * - `worker-src blob:`: MapLibre GL spawns its tessellation workers from
 *   blob URLs.
 */

/** Request header carrying the per-request CSP nonce into the RSC render. */
export const CSP_NONCE_HEADER = "x-nonce";

/**
 * Ship the policy as `Content-Security-Policy-Report-Only` instead of
 * enforcing. Flipped to `false` on 2026-06-11 after the report-only rollout
 * surfaced exactly one violation class (Zod's `new Function` JIT probe,
 * removed via `src/lib/zod-jitless.ts`) and a full e2e pass ran clean.
 */
export const CSP_REPORT_ONLY = false;

/** External origins, grouped by directive. */
const SUPABASE_HTTPS = "https://*.supabase.co";
const SUPABASE_WSS = "wss://*.supabase.co";
const GOOGLE_AVATARS = "https://lh3.googleusercontent.com";
const OPENFREEMAP = "https://tiles.openfreemap.org";
const SENTRY_INGEST = "https://*.ingest.sentry.io";
const SENTRY_INGEST_US = "https://*.ingest.us.sentry.io";

/**
 * Build the full policy string for one request.
 *
 * @param nonce - Per-request random value generated by the proxy.
 */
export function buildContentSecurityPolicy(nonce: string): string {
  const directives: readonly (readonly [string, readonly string[]])[] = [
    ["default-src", ["'self'"]],
    ["script-src", ["'self'", `'nonce-${nonce}'`, "'strict-dynamic'"]],
    ["style-src", ["'self'", "'unsafe-inline'"]],
    ["img-src", ["'self'", "data:", "blob:", GOOGLE_AVATARS, SUPABASE_HTTPS]],
    [
      "connect-src",
      [
        "'self'",
        SUPABASE_HTTPS,
        SUPABASE_WSS,
        OPENFREEMAP,
        SENTRY_INGEST,
        SENTRY_INGEST_US,
      ],
    ],
    ["worker-src", ["'self'", "blob:"]],
    ["font-src", ["'self'", "data:"]],
    ["object-src", ["'none'"]],
    ["base-uri", ["'self'"]],
    ["form-action", ["'self'"]],
    ["frame-ancestors", ["'none'"]],
  ];
  return directives
    .map(([directive, values]) => `${directive} ${values.join(" ")}`)
    .join("; ");
}
