-- Tracker Phase 0:
-- Seed the immunization schedule per Buku KIA 2024 hal. 124-125. Covers the
-- mandatory infant schedule (0-18 months). The `display_order` column drives
-- the timeline ordering in the UI. All inserts are idempotent (upsert by code).
--
-- Vaccine codes follow Kemenkes nomenclature (HB0, BCG, OPV1..4, IPV1..2,
-- DPT-HB-Hib-1..4, PCV1..3, RV1..3, MR1..2, JE). The `prevents` column is
-- populated here so the tracker UI can render the educational tooltip.

INSERT INTO public.immunization_schedule
  (code, name, dose_number, recommended_age_months, notes, display_order, prevents)
VALUES
  ('HB0', 'Hepatitis B (HB0)', 1, 0,
    'Diberikan dalam 24 jam pertama setelah lahir.',
    10,
    'Hepatitis B dan kanker hati.'),
  ('BCG', 'BCG', 1, 1,
    'Mencegah Tuberkulosis (TBC) berat.',
    20,
    'Tuberkulosis (TBC), termasuk bentuk berat seperti TBC otak dan TBC tulang.'),
  ('OPV1', 'Polio tetes (OPV) 1', 1, 1,
    NULL,
    30,
    'Polio (lumpuh layu pada tungkai atau lengan).'),
  ('DPT-HB-Hib-1', 'DPT-HB-Hib 1', 1, 2,
    NULL,
    40,
    'Difteri, Pertusis (batuk rejan), Tetanus, Hepatitis B, serta Pneumonia dan Meningitis akibat bakteri Hib.'),
  ('OPV2', 'Polio tetes (OPV) 2', 2, 2,
    NULL,
    50,
    'Polio (lumpuh layu pada tungkai atau lengan).'),
  ('PCV1', 'PCV 1', 1, 2,
    NULL,
    60,
    'Pneumonia akibat bakteri pneumokokus.'),
  ('RV1', 'Rotavirus 1', 1, 2,
    NULL,
    70,
    'Diare berat dan dehidrasi akibat rotavirus.'),
  ('DPT-HB-Hib-2', 'DPT-HB-Hib 2', 2, 3,
    NULL,
    80,
    'Difteri, Pertusis (batuk rejan), Tetanus, Hepatitis B, serta Pneumonia dan Meningitis akibat bakteri Hib.'),
  ('OPV3', 'Polio tetes (OPV) 3', 3, 3,
    NULL,
    90,
    'Polio (lumpuh layu pada tungkai atau lengan).'),
  ('PCV2', 'PCV 2', 2, 3,
    NULL,
    100,
    'Pneumonia akibat bakteri pneumokokus.'),
  ('RV2', 'Rotavirus 2', 2, 3,
    NULL,
    110,
    'Diare berat dan dehidrasi akibat rotavirus.'),
  ('DPT-HB-Hib-3', 'DPT-HB-Hib 3', 3, 4,
    NULL,
    120,
    'Difteri, Pertusis (batuk rejan), Tetanus, Hepatitis B, serta Pneumonia dan Meningitis akibat bakteri Hib.'),
  ('OPV4', 'Polio tetes (OPV) 4', 4, 4,
    NULL,
    130,
    'Polio (lumpuh layu pada tungkai atau lengan).'),
  ('IPV1', 'Polio suntik (IPV) 1', 1, 4,
    NULL,
    140,
    'Polio (lumpuh layu pada tungkai atau lengan).'),
  ('RV3', 'Rotavirus 3', 3, 4,
    NULL,
    150,
    'Diare berat dan dehidrasi akibat rotavirus.'),
  ('MR1', 'Campak-Rubela (MR) 1', 1, 9,
    NULL,
    160,
    'Campak dan Rubela.'),
  ('IPV2', 'Polio suntik (IPV) 2', 2, 9,
    NULL,
    170,
    'Polio (lumpuh layu pada tungkai atau lengan).'),
  ('JE', 'Japanese Encephalitis (JE)', 1, 10,
    'Hanya untuk daerah endemik Japanese Encephalitis.',
    180,
    'Japanese Encephalitis (radang otak).'),
  ('PCV3', 'PCV 3', 3, 12,
    NULL,
    190,
    'Pneumonia akibat bakteri pneumokokus.'),
  ('DPT-HB-Hib-4', 'DPT-HB-Hib 4 (lanjutan)', 4, 18,
    'Imunisasi lanjutan untuk memperkuat kekebalan.',
    200,
    'Difteri, Pertusis (batuk rejan), Tetanus, Hepatitis B, serta Pneumonia dan Meningitis akibat bakteri Hib.'),
  ('MR2', 'Campak-Rubela (MR) 2 (lanjutan)', 2, 18,
    'Imunisasi lanjutan untuk memperkuat kekebalan.',
    210,
    'Campak dan Rubela.')
ON CONFLICT (code) DO UPDATE
  SET
    name = EXCLUDED.name,
    dose_number = EXCLUDED.dose_number,
    recommended_age_months = EXCLUDED.recommended_age_months,
    notes = EXCLUDED.notes,
    display_order = EXCLUDED.display_order,
    prevents = EXCLUDED.prevents,
    updated_at = now();
